ls1intum/Hephaestus

- package.json
- scripts/clean-openapi-specs.js
- server/application-server/openapi.yaml
- webapp/src/app/core/modules/openapi/.openapi-generator/FILES
- webapp/src/app/core/modules/openapi/api/admin.service.ts
- webapp/src/app/core/modules/openapi/api/admin.serviceInterface.ts
- webapp/src/app/core/modules/openapi/api/api.ts
- webapp/src/app/core/modules/openapi/api/hello.service.ts
- webapp/src/app/core/modules/openapi/api/hello.serviceInterface.ts
- webapp/src/app/example/hello/hello.component.ts
Remove controller from API client it is now `HelloService` instead of `HelloControllerService`
> Improve naming of OpenAPI client services

- webapp/src/app/example/counter/counter.component.ts
- webapp/src/app/example/hello/hello.component.ts
- webapp/src/app/ui/button/button.component.ts
- webapp/src/app/ui/button/button.stories.ts
- webapp/src/app/ui/input/input.component.ts
- webapp/src/app/ui/input/input.stories.ts
- webapp/src/app/ui/label/label.component.ts
- webapp/src/app/ui/label/label.stories.ts
Remove unnecessary `App` prefix for components for consistency, we only need it in the template to avoid colliding with html tags.
> Remove App prefix for components

- webapp/.storybook/preview.ts
- webapp/src/app/app.component.html
- webapp/src/app/app.component.ts
- webapp/src/app/app.config.ts
- webapp/src/app/components/theme-switcher/theme-switcher.component.html
- webapp/src/app/components/theme-switcher/theme-switcher.component.ts
- webapp/src/app/components/theme-switcher/theme-switcher.service.ts
- webapp/src/app/components/theme-switcher/theme-switcher.stories.ts
- webapp/src/index.html
- Automatically switch to current system theme preference and store it in local storage
- Add theme switcher component
- Test out angular animations
- Add component to header and improve it
#28
Light:
Dark:
> Add theme switcher to header

- server/application-server/pom.xml
- server/application-server/src/main/java/de/tum/in/www1/hephaestus/Application.java
- server/application-server/src/test/java/de/tum/in/www1/hephaestus/HephaestusApplicationTests.java
- server/application-server/src/test/java/de/tum/in/www1/hephaestus/HephaestusModulithTests.java
Spring Modulith allows for module-driven development in a Spring project including internal and API-exposed parts within a module. It provides event management for cross-module communication and integration testing functionality.
Adds the core packages of Spring Modulith to the Application Server.
Added tests include a module integrity verification (according to https://docs.spring.io/spring-modulith/reference/verification.html) as well as UML diagram generation.
- https://docs.spring.io/spring-modulith/reference/appendix.html#artifacts
> Integrate Spring Modulith in `application-server`

- webapp/Dockerfile
`.env` is `.env-pr-63` for example during preview deployments with Coolify
Move `.env*` to `.env` during build
> Fix build env for webapp preview deployments

- server/webhook-ingest/app/logger.py
- server/webhook-ingest/app/main.py
- server/webhook-ingest/app/nats_client.py
- server/webhook-ingest/compose.yaml
Fixes #64 and fixes #65
- Add sanitization for the subject to replace `.` with `~`
- Retry publish to NATS on error
> Add subject sanitization and retry to publish on error

- .github/workflows/webapp-qa.yml
We want to avoid unnecessary workflow executions by limiting its trigger conditions.
This PR excludes the OpenAPI auto-generated folder from the trigger conditions for the workflow. 
In cases where changes in the application server require a OpenAPI Spec re-generation, this workflow should not be needed. 
Both ESLint and Prettier are configured to ignore the openapi folder, so a workflow execution is redundant and should be guaranteed to not provide any new results.
> Workflow: Exclude OpenAPI folder from Webapp QA workflow

- server/application-server/src/main/resources/application-prod.yml
Provides a default production assignment to the Github auth token, which is used for fetching data from Github.
Assigns the environment variable `GITHUB_AUTH_TOKEN` in the Spring application when using the production profile.
> Add Github AuthToken to application-prod.yml

- .github/workflows/generate-api-client.yml
- package.json
- server/application-server/openapi.yaml
- server/application-server/src/main/java/de/tum/in/www1/hephaestus/hello/HelloController.java
- server/application-server/src/main/java/de/tum/in/www1/hephaestus/hello/HelloService.java
- webapp/src/app/core/modules/openapi/api/hello.service.ts
- webapp/src/app/core/modules/openapi/api/hello.serviceInterface.ts
Closes #72 
You can add label `autocommit-openapi` to automatically let a GitHub workflow commit the updated specs and api clients
> Add workflow to generate API specs and clients with a manual trigger

- server/application-server/src/main/java/de/tum/in/www1/hephaestus/codereview/base/Comment.java
- server/application-server/src/main/java/de/tum/in/www1/hephaestus/scheduler/GitHubDataSyncScheduler.java
Guarantee the Github sync only runs after the server has started and is available.
Replaces the `ApplicationRunner` with an `EventLister` for the `ApplicationReadyEvent` event.
> Replace `ApplicationRunner` with `EventListener` to fix startup time

- webapp/.storybook/preview.ts
- webapp/package-lock.json
- webapp/package.json
- webapp/src/app/components/theme-switcher/theme-switcher.service.ts
- webapp/src/index.html
- webapp/src/styles.css
- webapp/tailwind.config.ts
Github's design system's colors are openly available and we can make use of them.
Integrated GitHub's design system colors and created tailwind colors for it.
> Add Github colors to Tailwind

- server/application-server/src/main/java/de/tum/in/www1/hephaestus/leaderboard/LeaderboardService.java
This PR fixes stats for the leaderboard.
- the score calculation formula was missing a divison by 10
- `dismissed`-reviews are no longer counted as comment (`commented`-state)
The original Python script goes a step further and backtraces `dismissed`-reviews to their original state. For now I was unable to figure out how to translate this behavior to our API-Wrapper, we might be able to do this in a follow-up.
> Fix: Score calculation and avoid counting 'dismissed'-reviews as comments

- webapp/src/app/home/leaderboard/leaderboard.component.html
Fixes a bug with the `alt`-attribute of the avatar component usage for the leaderboard.
Before:
After:
> Fix: Avatar alt string template

- server/application-server/src/main/java/de/tum/in/www1/hephaestus/WebConfig.java
- server/application-server/src/main/java/de/tum/in/www1/hephaestus/scheduler/GitHubDataSyncService.java
Seperating the server logic across dedicated files often helps keep files clean and understandable. Our type converters can easily be handled by Spring itself, making manual handling obsolete.
This PR adds all our type converters to a dedicated `WebMvcConfigurer` making it possible to be autowired whenever necessary. This cleans up a lot of boilerplate code of our `GitHubDataSyncService`-constructor, letting Spring handle the injection.
Source: https://www.baeldung.com/spring-type-conversions#creating-a-custom-converter
> Autowire Converters in WebMVC

- webapp/package-lock.json
- webapp/package.json
- webapp/src/app/home/home.component.ts
Closes #107.
We now use the current week as default whenever there are no query params. This should have been part of the original PR #105, but I must have missed it.
It also fixes the Dayjs package version, which got merged with a `^` in #92.
> Fix: Initial Leaderboard filter params

- webapp/src/app/home/leaderboard/filter/filter.component.ts
Fixes #107 but for the new Spartan select component.
With the new implementation of the select component, the scoreboard always skips to the newest timeframe options after a page refresh instead of keeping the state from the URL.
This PR fixes this issue by avoiding a navigation before the old query params are retrieved.
> Fix: Wait for Leaderboard params init

- server/application-server/src/main/java/de/tum/in/www1/hephaestus/scheduler/GitHubDataSyncService.java
The CRON-job execution currently fails with a `LazyInitializationException` leading to incorrect data updates and subsequent lack to data in the database.
Makes the scheduling `transactional` again to allow for arbitarity database access. This is required as some relations are only fetched lazily, requiring on-demand fetching during the scheduled task. 
Has been tested as Preview Deployment in Coolify, but not with the production DB.
For future reference: transactions can be customized via [Sessions](https://docs.jboss.org/hibernate/orm/3.5/javadocs/org/hibernate/Session.html).
> Fix: `LazyInitializationException` in CRON-job execution

- webapp/src/app/home/home.component.html
- webapp/src/app/home/leaderboard/filter/filter.component.html
- webapp/src/app/home/leaderboard/filter/repository/repository.component.ts
On smaller screens (e.g. mobile) the leaderboard filters are sometimes outside of the viewing area.
This PR gives the filter component more responsiveness for smaller screens.
Width <580px:
Width 580-1280px:
> Fix: Improve filter layout for mobile

- webapp/src/app/home/home.component.ts
- webapp/src/app/home/leaderboard/filter/timeframe/timeframe.component.ts
Fixes a bug where the leaderboard timeframe is incorrect on the starting day of a new leaderboard cycle.
Currently, there is a bug which causes the week to be displayed incorrectly on the same day of the new leaderboard cycle:
This PR additionally also changes:
- Time of the day is now displayed
- The "before" of the active leaderboard week is now displayed as "Now". "Now" is only shown for a "before" within the same hour
**Interesting behavior:**
Currently the leaderboard data is not refreshed ("up-to-date") when switching select-options due to our initial determination of dates. For example if we switch back to the "current week" after leaving the page open for a few minutes, our data will still be the same as it was when accessing the "current week" for the first time. Only a …
> Fix: Timeframe Same Day Detection

- server/application-server/src/main/java/de/tum/in/www1/hephaestus/Application.java
We want to change the timezone of the server to correctly schedule CRON-jobs, such as the scheduled Slack message.
This PR sets the timezone to `Europe/Berlin`, which resolves to UTC+1/+2 handling daylight saving time automatically.
Has been tested as preview deployment on the server:
Nothing to test really
> Fix: Changing Server Timezone

- package-lock.json
- package.json
Liquibase has proven to be more difficult than expected. We want to make the devloper experience when changing the database schema as seamless as possible.
This PR changes the following:
- Enhance `db:changelog:diff` to better reflect the process required for a successful changelog generation
- make sure the database is cleanly restarted before using Liquibase
- current `postgres-data` is temporily renamed to `postgres-data-temp` to avoid data loss in the process
- Remove `rimraf` in favor of `shx`
- Run `npm run db:changelog:diff` and check for an error-free execution
> Improve Liquibase changelog generation

- server/application-server/openapi.yaml
- server/application-server/src/main/java/de/tum/in/www1/hephaestus/leaderboard/LeaderboardEntryDTO.java
- server/application-server/src/main/java/de/tum/in/www1/hephaestus/leaderboard/LeaderboardService.java
- webapp/src/app/core/modules/openapi/model/leaderboard-entry.ts
- webapp/src/app/home/leaderboard/leaderboard.component.html
- webapp/src/app/home/leaderboard/leaderboard.component.ts
- webapp/src/app/home/leaderboard/leaderboard.stories.ts
- webapp/src/app/home/leaderboard/reviews-popover/reviews-popover.component.html
- webapp/src/app/home/leaderboard/reviews-popover/reviews-popover.component.ts
- webapp/src/app/home/leaderboard/reviews-popover/reviews-popover.stories.ts
Our Confluence meeting pages require listing your reviewed PRs. To ease this process, we want to provide the functionality of pasting all reviewed PRs within a certain timeframe.
This PR adds a popover to the "total reviewed PRs" displaying a list of the reviewed PRs. Additionally, it provides a copy-button to copy the list in a HTML-based format.
- Run the `application-server` and `webapp`
- Click on the new "total reviewed PRs"-button and scroll through the list of PRs
- Click on the copy-button and test the formatting by pasting it on Confluence
> Popover for reviewed PRs & Copy-Button

- server/application-server/src/main/java/de/tum/in/www1/hephaestus/config/NatsConfig.java
If the NATS-server is unavailable, running the application-server will still fail due to unrelated connection attempts even if it's disabled. We want to make sure setting "nats.enabled: false" means there is no connection to the NATS-server made at all.
During Application Startup, there are connection attempts made regardless of the `nats.enabled`-setting. This PR adds an additional check to avoid initializing the `@Bean` for the NATS-server when `nats.enabled` is set to `false`.
- Enter an invalid connection-string in `application-local.yml` -> `nats.server` and set `nats.enabled` to `false`.
- Start the `application-server` and check if it starts without errors
> Fix: No Nats Connection Attempts if Disabled

- webapp/src/app/home/home.component.ts
Fixes a bug where the new leaderboard did not get shown per default on it's first day.
When using no leaderboard parameters, the defaults still displayed last week's leaderboard instead of the new one.
- Start `application-server` and `webapp`
- Check if the default page displays the current leaderboard (only relevant on Tuesdays)
> Fix: Show new Leaderboard instantly

- server/application-server/keycloak-hephaestus-realm-example-config.json
- server/application-server/openapi.yaml
- server/application-server/pom.xml
- server/application-server/src/main/java/de/tum/in/www1/hephaestus/OpenAPIConfiguration.java
- server/application-server/src/main/java/de/tum/in/www1/hephaestus/config/KeycloakConfig.java
- server/application-server/src/main/java/de/tum/in/www1/hephaestus/gitprovider/user/UserController.java
- server/application-server/src/main/resources/application-prod.yml
- server/application-server/src/main/resources/application.yml
- webapp/src/app/app.routes.ts
- webapp/src/app/core/header/header.component.html
- webapp/src/app/core/header/header.component.ts
- webapp/src/app/core/modules/openapi/api/user.service.ts
- webapp/src/app/core/modules/openapi/api/user.serviceInterface.ts
- webapp/src/app/settings/settings.component.ts
We need to let users delete their account to be compliment with GDPR. 
- Add setting page
- Add setting button to user menu
- Add endpoint to delete user (currently just the keycloak user)
- Fix `void` response for OpenAPI
- Update default keycloak config data with a correctly setup admin client
Create an account and delete it via the settings.
> Add settings page to delete user

- .github/workflows/application-server-qa.yml
After changes in the `package.json` the GitHub workflow running prettier stopped working due to changed command name.
> Fix of the GitHub workflow application-server-qa

- webapp/src/app/home/home.component.ts
- webapp/src/app/home/leaderboard/filter/timeframe/timeframe.component.ts
- webapp/src/app/workspace/teams/table/teams-table.component.ts
Fixes an issue where the after param is after the before param due to the week starting on Tuesdays. I.e. https://hephaestus.ase.cit.tum.de redirects to https://hephaestus.ase.cit.tum.de/?after=2024-11-26T09:00:00%2B01:00&before=2024-11-25T00:22:47%2B01:00 right now, making the default leaderboard data incorrect.
This fix moves the default date configuration to the leaderboard filter component, making sure dates are only changed in one place of the application.
Also fixes a small bug regarding the recently merged PR #124, where the default value of the Team-Color-Input had an invalid default value:
- Run `application-server` and `webapp`
- Go to `http://localhost:4200/` and check if the default leaderboard uses the correct timeframe.
> Fix: Use correct After-queryParam when none specified

- webapp/src/app/home/home.component.ts
- webapp/src/app/home/leaderboard/filter/timeframe/timeframe.component.ts
Fixes a bug where the timeframe parameters assumed invalid states on browser tab change or same page-navigation, i.e. when clicking on the logo in the header.
This PR is a follow-up to #188 and fixes:
- after/before-param consistency in the URL:
- when switching tabs
- when navigating on the same page (e.g. removing query params without changing the page -> revelant for Hephaestus-logo in header) go back to default timeframe (i.e. current week)
- remove state logic from home component and move to timeframe component
- incorrect time ranges in current week ("Custom Range") - now uses the actual end date of the week instead of current minute
- Run `application-server` and `webapp`
- Navigate through different leaderboards
- Use the Hephaestus-Logo and check if you get navigated back to the …
> Fix: Timeframe Parameter Consistency on Navigation

- webapp/src/app/core/security/keycloak.service.ts
Currently, users are forced to refresh the Hephaestus-Website (every 30 minutes) when the access token expires and subsequent requests include invalid authentication/JWT token.
This PR fixes the token expiry issue by adding a refresh interval checking for expiry every 60 seconds. Keycloak then refreshes the token itself (triggers a new request to the Keycloak-server).
The PR implements ideas from this best practices guide: https://github.com/akoserwal/keycloak-integrations/blob/main/angular-keycloak/src/main.ts
Additional security suggestions from this [Medium article](https://medium.com/@elamarane90/keycloak-session-configuration-best-practices-and-principles-cdff9348f936) could indepently used for higher security.
- Run `application-server` and `webapp`
- Login on the website
- Wait for …
> Fix: Keycloak Refresh Tokens before Expiry

- server/application-server/src/main/java/de/tum/in/www1/hephaestus/meta/MetaService.java
- webapp/src/app/home/leaderboard/filter/team/team.component.ts
The current list of teams in the "Select team"-filter can be super confusing due to a lack of ordering.
This PR sorts the list of teams in the metadata (GET `/meta`) alphabetically. The "all"-option will nevertheless always stay the first one and is selected as default.
> Fix: Sort Teams in Metadata alphabetically

- server/application-server/src/main/java/de/tum/in/www1/hephaestus/leaderboard/LeaderboardTaskScheduler.java
- server/application-server/src/main/java/de/tum/in/www1/hephaestus/leaderboard/SlackMessageService.java
- server/application-server/src/main/java/de/tum/in/www1/hephaestus/leaderboard/tasks/SlackWeeklyLeaderboardTask.java
For future features (such as the leaderboard leagues) we need to be able to execute tasks easily at the end of each leaderboard cycle.
Implements task 3.1 of #170.
This PR reworks the original task scheduler used for the weekly Slack message to be more modular (separating the logic) and easily support adding new tasks:
- `LeaderboardTaskScheduler` now manages all tasks and schedules them for the end of a leaderboard cycle
- `SlackMessageService` is now only a light wrapper around the `SlackAppConfig`, providing implementations for sending messages and testing the connection
- `SlackWeeklyLeaderboardTask` is a runnable task, scheduled by the `LeaderboardTaskScheduler`, responsible for creating the Slack message and delegating the sending process
No manual testing required - Code reviews …
> `Refactor`: Modularization of Task Scheduling

- server/application-server/pom.xml
- server/application-server/src/main/java/de/tum/in/www1/hephaestus/config/SentryConfiguration.java
- server/application-server/src/main/resources/application-prod.yml
- server/application-server/src/main/resources/application.yml
Solves task 1 of #202.
This PR adds Sentry to our Spring-Boot Server:
- https://sentry.ase.in.tum.de/organizations/aet/projects/hephaestus/?project=3
- set the Sentry DSN via `sentry.dsn` in the application-file
- disabled in _spec_-profile
- environment-based sample rate (adapted from Artemis, see [SentryConfiguration.java](https://github.com/ls1intum/Artemis/blob/develop/src/main/java/de/tum/cit/aet/artemis/core/config/SentryConfiguration.java)):
- test: 1.0 (for when we have real production-like test servers / preview deployments)
- prod: 0.2
- local: 0 (don't spam Sentry with errors during development)
- new env-var for the Hephaestus release (we should update this accordingly from time to time)
Example test errors: 
- https://sentry.ase.in.tum.de/share/issue/18f5961403d34efc90d23356f8 …
> Add Sentry Configuration to `application-server`

- server/application-server/src/main/java/de/tum/in/www1/hephaestus/leaderboard/LeaderboardService.java
- server/application-server/src/main/java/de/tum/in/www1/hephaestus/leaderboard/ScoringService.java
Fixes https://ls1tum.slack.com/archives/C07CZNLULQN/p1733604651504789
This PR fixes bugs where:
- issue comments on own PRs count towards the total leaderboard score
- activity on own PRs were assigned with more than 0 points on the profile/user page
- own PRs were not filtered correctly from the list of reviewed PRs
Test by comparing this week's leaderboard:
`SimonEntholzer` has more than 500 points on https://hephaestus.ase.cit.tum.de, with this PR his points should be reduced to about 300.
> Fix: Ignore own Issue Comments for Score Calculation

- webapp/src/app/user/user-profile.component.ts
- webapp/src/app/user/user-profile.stories.ts
Fixes #208.
This fix makes sure profile pages listen to URL changes.
- Go to a random user page, such as http://localhost:4200/user/SimonEntholzer
- Open the user menu and navigate to your own profile
- Page should switch to our own profile page
> Fix: Persist User Change on Navigation

- .github/workflows/generate-intelligence-service-client.yml
- .github/workflows/intelligence-service-qa.yml
- server/intelligence-service/Dockerfile
- server/webhook-ingest/Dockerfile
Fixes incompatibility issues caused by the Poetry v2.0 release.
Locks the Poetry version installed by Docker and the Github Action workflows to version 1.8.5, the last version before the breaking 2.0 release.
> Fix: Lock Poetry version to 1.8.5

- webapp/src/app/home/leaderboard/leaderboard.component.html
Fixes a visual bug caused by the addition of leagues to the leaderbord, where the placeholder for the "empty data"-state was not spanning all columns
Before this PR:
After this PR:
> Fix: Colspan of Leaderboard Empty Data-State

- webapp/src/app/ui/league/icon/league-bronze-icon.component.ts
- webapp/src/app/ui/league/icon/league-diamond-icon.component.ts
- webapp/src/app/ui/league/icon/league-gold-icon.component.ts
- webapp/src/app/ui/league/icon/league-icon.component.ts
- webapp/src/app/ui/league/icon/league-icon.stories.ts
- webapp/src/app/ui/league/icon/league-master-icon.component.ts
- webapp/src/app/ui/league/icon/league-none-icon.component.ts
- webapp/src/app/ui/league/icon/league-silver-icon.component.ts
- webapp/src/styles.css
This pull request includes significant updates to the league icon components in the web application. The changes involve the addition of new league icon components, modifications to the main league icon component to incorporate these new components, and updates to the styling and storybook configuration.
* Added `LeagueBronzeIconComponent`, `LeagueDiamondIconComponent`, `LeagueGoldIconComponent`, `LeagueMasterIconComponent`, `LeagueNoneIconComponent`, and `LeagueSilverIconComponent` with their respective SVG templates. [[1]](diffhunk://#diff-4379e00691a304255c3c546783f681c8a3a080abf593dbcc9c00b9585db4109eR1-R19) [[2]](diffhunk://#diff-41015e68a4b0d7dd5bcfb57b370b624e33665981e3f03c18c65ecfffb680e455R1-R24) [[3]](diffhunk://#diff-eeab0bebc954d3e8b2483f9e0128a04558e538f69e08c2f6615c1fe71c80b0 …
> Add new league icons

- server/application-server/src/main/java/de/tum/in/www1/hephaestus/activity/badpracticedetector/BadPracticeDetectorScheduler.java
- server/application-server/src/main/java/de/tum/in/www1/hephaestus/activity/badpracticedetector/PullRequestBadPracticeDetector.java
- server/application-server/src/main/java/de/tum/in/www1/hephaestus/intelligenceservice/model/DetectorRequest.java
- server/application-server/src/main/resources/mail-templates/bad-practices-detected.html
- server/intelligence-service/app/detector/bad_practice_detector.py
- server/intelligence-service/app/routers/detector.py
- server/intelligence-service/openapi.yaml
- webapp/src/app/app.routes.ts
- webapp/src/app/core/header/header.component.html
- webapp/src/app/home/activity/activity-dashboard.component.ts
- webapp/src/app/user/pull-request-bad-practice-card/pull-request-bad-practice-card.component.ts
This pull request introduces several updates to enhance functionality, improve error handling, and streamline the user interface for bad practice detection in pull requests. The changes span across the backend, frontend, and email templates, focusing on adding new fields for better traceability, refining scheduling logic, and updating user-facing routes and templates.
* **Improved Error Logging**:
- Updated error logging in `checkUserRoleAndScheduleDetectionAtTime` to use `e.toString()` for more detailed exception information. (`BadPracticeDetectorScheduler.java`, [server/application-server/src/main/java/de/tum/in/www1/hephaestus/activity/badpracticedetector/BadPracticeDetectorScheduler.javaL130-R130](diffhunk://#diff-24f2bc165a36ed3b03e3bbb2bfa4cd621f6450680efa6c8d7ac65ac0f9f61d86L130-R13 …
> Remove admin guard in header
